# Generated by Django 4.0.1 on 2022-01-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('leave', '0002_leave_is_approved_leave_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='department',
            field=models.ManyToManyField(to='Employee.Department', verbose_name='Department'),
        ),
    ]
