# Generated by Django 4.0.1 on 2022-01-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leave_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='department',
        ),
        migrations.AddField(
            model_name='leave',
            name='department',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='department'),
        ),
    ]
