# Generated by Django 4.0.1 on 2022-01-16 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_remove_leave_department_leave_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='applied_date',
            field=models.DateField(default=datetime.date.today, verbose_name='applied_date'),
        ),
    ]
