# Generated by Django 4.0 on 2022-01-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_alter_employee_user'),
        ('Employee', '0004_auto_20211230_2345'),
    ]

    operations = [
    ]
