# Generated by Django 4.0.1 on 2022-01-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_alter_employee_user'),
        ('Employee', '0006_employee_image_alter_employee_user'),
    ]

    operations = [
    ]
