# Generated by Django 4.0.1 on 2022-01-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Termination_date', models.DateField()),
                ('Prim_reason', models.CharField(max_length=150)),
                ('sec_reason', models.CharField(max_length=150)),
                ('attachment', models.FileField(upload_to='resignation')),
            ],
        ),
    ]
