# Generated by Django 4.0.1 on 2022-01-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resignation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resignation',
            old_name='Prim_reason',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='resignation',
            name='sec_reason',
        ),
    ]
