# Generated by Django 4.0.1 on 2022-01-16 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resignation', '0004_resignation_is_approved_resignation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignation',
            name='applied_date',
            field=models.DateField(default=datetime.date(2022, 1, 16)),
        ),
    ]
