# Generated by Django 4.0.1 on 2022-01-16 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Resignation', '0005_resignation_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='applied_date',
            field=models.DateField(default=datetime.datetime(2022, 1, 16, 12, 9, 29, 876442, tzinfo=utc)),
        ),
    ]
