# Generated by Django 4.0.1 on 2022-01-16 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Resignation', '0006_alter_resignation_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='applied_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
