# Generated by Django 3.0.8 on 2022-01-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resignation', '0007_alter_resignation_applied_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resignation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
