# Generated by Django 4.0.1 on 2022-01-29 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resignation', '0009_alter_resignation_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resignation',
            name='attachment',
        ),
    ]
