# Generated by Django 3.0.8 on 2022-01-18 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(help_text='Heading for the task', max_length=30, null=True, verbose_name='Title')),
                ('description', models.TextField(help_text='Description for the task', max_length=255, null=True, verbose_name='Description')),
                ('assign_date', models.DateField(help_text='task assignment day', null=True, verbose_name='assign date')),
                ('deadline', models.DateField(help_text='task deadline', null=True, verbose_name='deadline')),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=25)),
                ('is_approved', models.BooleanField(default=False)),
                ('department', models.CharField(default=None, max_length=30, null=True, verbose_name='department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
