# Generated by Django 4.0.1 on 2022-01-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_remove_task_department_remove_task_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
